### PR TITLE
add metrics data backend support

### LINKED ISSUE #233: build a stats / metrics page on comses.net
Examples:

http://ascl.net/dashboard

https://csdms.colorado.edu/wiki/CSDMS_in_numbers

https://ui.adsabs.harvard.edu

1. let people see how their personal statistics have changed over time (eg downloads over time) 
2. figure out how to query citation data for a model (maybe only if they have DOIs)

### PR DESCRIPTION
**Pull request by alee**
closes #233 
closes comses/planning#86

### CODE REVIEW

**Comment by alee** [comment]
uhoh @hwelsters looks like you committed the cardinal sign of merging main back into your feature branch.

**Comment by hwelsters** [comment]
Oh no. Sorry, I clicked on Sync fork without thinking.

**Comment by alee** [comment]
No problem! Good work fixing it, it might be valuable to demo how to rebase / rewrite history for the rest of the @comses/comses-student-devs and Port of Mars devs tomorrow.

You can recreate this scenario on a local fork or repository - 

1. create a feature branch
2. make changes to the feature branch *and* the main branch
3. merge the changes in the main branch into the feature branch
4. fix through `git rebase -i` or a git client that supports interactive rebasing and force push back to your feature branch

**Comment by alee** [comment]
closing in favor of #628

**Pull request closed without merging**
