### PR TITLE
Additional UI changes/fixes for release detail page

### PR DESCRIPTION
**Pull request by sgfost**
#### Changes
- reduce global border radius
- slightly lighten metadata sidebar/blocks color
- show private info on unpublished releases with change perms
- clean up metadata sidebar formatting
- add framework and remove 'dependencies' from sidebar
- replace lang/framework with publish dates in subheader metadata
- add image gallery for codebases with multiple images uploaded

---

- [x] resolves comses/planning#128
- [x] resolves comses/planning#126
- [x] resolves comses/planning#132

### CODE REVIEW

**Comment by sgfost** [comment]
example:
release detail - https://staging.comses.net/codebases/6ade3057-9392-4eda-849d-995407b67acb/releases/8.0.0/
corresponding discussion - https://staging-discourse.comses.net/t/short-title/165

**Comment by alee** [comment]
> example: release detail - https://staging.comses.net/codebases/6ade3057-9392-4eda-849d-995407b67acb/releases/8.0.0/ corresponding discussion - https://staging-discourse.comses.net/t/short-title/165

Looks good! Should we consider including a few other metadata fields:

## Codebase

- references_text
- replication_text
- repository_url

## CodebaseRelease

- doi_url
- platform_tags / programming_languages
- license
- output_data_url (though this reminds me that I don't think we ever finished wiring that field up to the UI... it's intended to be a permanent URL / DOI to a landing page for where the model's simulation outputs have been archived)

Might not need all of them but.. maybe?

**Comment by sgfost** [comment]
I was going for a more minimal post and just assume people would follow the link to the model in the library for more details, though I'm not opposed to copying over more info. Can see what others' thoughts are

While we're on it, the repo url should probably get added to the sidebar and `output_data_url` can be put into the release metadata form

**Comment by sgfost** [comment]
Still some things to discuss and figure out here but the image gallery was the last feature/addition I wanted to add to this PR

how it looks:

Screenshot from 2023-07-24 17-53-02

**Pull request merged**
