### PR TITLE
improve mobile layout

### PR DESCRIPTION
**Pull request by chrstngyn**
added improve mobile layout and fixed dismissable alert

issues #462 #229

### CODE REVIEW

**Comment by chrstngyn** [comment]
Navbar in desktop view with 2-row navbar.

Screenshot from 2019-07-24 14-32-06

There's a lot of white space in between the two logos and navbar-links. I tried both responsive classes and writing custom responsive css to resolve the white space, but that messed with the mobile layout. Do you want me to continue looking for solutions to fix this?

**Comment by alee** [comment]
> There's a lot of white space in between the two logos and navbar-links. I tried both responsive classes and writing custom responsive css via media queries to resolve the white space, but that messed with the mobile layout. Do you want me to continue looking for solutions to fix this?

It would be good to fix at some point but I think we can move on to other issues first.. will merge and test out on staging, thanks! :+1:

**Comment by alee** [comment]
Thanks for the updates @chrstngyn ! I set up a max-width with auto margins wrapping the entire navbar in the `.comses-navbar` class but it isn't triggering the hamburger menu in time before the links start looking weird when we shrink the viewport. Do you know how we can fix this? I'm still clueless as to how the hamburger menu toggles at the moment :sweat_smile:

**Comment by chrstngyn** [comment]
I'll look into it now

**Pull request merged**
