### PR TITLE
footer rework

### PR DESCRIPTION
**Pull request by sgfost**
Re-design of the footer to have a slightly more manageable section for funding/support logos. Includes some small tweaks to certain logos for the sake of coherence

Also adds shadows to banners with image backgrounds (intros, featured models, footer) for some depth but this is more subjective

desktop:

image

mobile:

image

### CODE REVIEW

**Comment by alee** [comment]
Looks a little weird on my browser:

image

**Comment by sgfost** [comment]
sure does.. Though it looks fine on my chrome. Cached stylesheets maybe? That's what it looks like if the changes to _home.scss are reverted

**Comment by sgfost** [comment]
Though vite should be cache busting, not sure how that would happen

**Comment by alee** [comment]
looks fine now after a ctrl+shift+r hard refresh

**Review by alee — APPROVED** [review]
thanks Scott! need to upgrade our social icons but that might go along with an upgrade to bootstrap 5 or major change migration to tailwind

**Comment by cmbarton** [comment]
Looks nice. We could the current reference to the E. Musk service seen in most news stories. "X (formerly known as Twitter)"

**Pull request merged**
