### PR TITLE
Wagtail 5 search fixes

### PR DESCRIPTION
**Pull request by sgfost**
resolves comses/planning#123

- [x] replace/migrate `Query` model: https://docs.wagtail.org/en/latest/releases/5.0.html#wagtailsearch-query-has-moved-to-wagtail-contrib-search-promotions

**management/migrations**:
- move wagtail search query models to new location
  - `./manage.py migrate wagtailsearchpromotions`
  - `./manage.py copy_daily_hits_from_wagtailsearch`
    - **(might want to archive before copying over due to the huge amt of records)**
- archive daily query hits
  - [search/0001](https://github.com/comses/comses.net/blob/0a2c50c4541547249cadd6bd1902b265188a296b/django/search/migrations/0001_initial_archived_queries.py) add `ArchivedQueryHits` (search hits grouped by year)
  - `./manage.py archive_search_query_hits` [[options](https://github.com/comses/comses.net/blob/0a2c50c4541547249cadd6bd1902b265188a296b/django/search/management/commands/archive_search_query_hits.py)]

### CODE REVIEW

**Comment by sgfost** [comment]
9ab1528 breaking `check_list()` tests, but only for profile/event/job and not codebase..

**Comment by sgfost** [comment]
Needed to use `search_backend.autocomplete()` only when we have a query that isnt `MatchAll`. Search functionality seems to be back in order now

**Comment by sgfost** [comment]
This involves a few migration steps to move everything over to the new Query model location (https://docs.wagtail.org/en/latest/releases/5.0.html#wagtailsearch-query-has-moved-to-wagtail-contrib-search-promotions):

```
./manage.py migrate wagtailsearchpromotions
```
```
./manage.py copy_daily_hits_from_wagtailsearch
```
```
./manage.py searchpromotions_garbage_collect
```

**Comment by alee** [comment]
should we merge this in before the vue3-replace PR #652 ?

**Comment by sgfost** [comment]
Sure, that order makes a bit more sense

**Review by alee — COMMENTED** [review]
After reading through https://docs.wagtail.org/en/stable/topics/search/searching.html more thoroughly I’m wondering if some of these autocomplete fields should be basic search fields instead..?

**Comment by sgfost** [comment]
I think you're right, my fault assuming most of this was a drop-in replacement for `partial_match`.

On second thought, maybe the frontend merge can go first while this gets revised and something for archiving query hits gets added (in the works now)

**Comment by sgfost** [comment]
Added a new command `archive_search_query_hits` which moves daily hits into a more condensed (grouped by year) table and then does the garbage collection on the daily hits and optionally queries table. This isn't scheduled to run currently but it could be a weekly/monthly thing

**Comment by sgfost** [comment]
As far as I can tell, removing `partial_match` and using regular `SearchField`s with the current search views seems to work just fine. Maybe that is the way to go and we can reserve AutocompleteField for its intended use?

**Comment by alee** [comment]
Sounds good to me! There's also support for facets now, so once we get tag cleaning done we can actually do some proper faceted searches across the model library

**Comment by sgfost** [comment]
I did a bit of messing around with the wagtail facets and they are pretty easy to drop in and use, only tricky bit will be adding specific language/framework filters

**Pull request merged**
