### PR TITLE
add user map of institutions (WIP)

### PR DESCRIPTION
**Pull request by CharlesSheelam**
-seperated codebase and codebase release total counts on the metrics table
-set up the backend to gather institution data for the user map

### CODE REVIEW

**Review by sgfost — CHANGES_REQUESTED** [review]
mostly structural stuff. LMK when the map is working and I'll take another look

**Review by sgfost — COMMENTED** [review]
We should capture the additional metadata from RoR when we make new entries. This should be an easy fix and I can do it in the next few hrs along with (hopefully) finding a better layout for the metrics page 

Everything else looks good. Thanks @CharlesSheelam and @alee for fixing.

**Comment by sgfost** [comment]
looks like this now:

Screenshot from 2024-12-11 20-11-56

**Review by alee — APPROVED** [review]
thanks @sgfost & @CharlesSheelam ! deployed on staging and lgtm

**Pull request merged**
