### PR TITLE
docs: create contributors guide

### PR DESCRIPTION
**Pull request by chrstngyn**
document ways in which members can contribute to the CoMSES Community

### CODE REVIEW

**Review by alee — CHANGES_REQUESTED** [review]
Hey Christine, I updated the comment on the issue recently, could you apply those changes here? 

I think it's good to have the changes directly in the README - we should also create a CONTRIBUTING.md file https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors that can be part of this same PR

**Comment by chrstngyn** [comment]
I will make those changes now and create a CONTRIBUTING.md

**Comment by chrstngyn** [comment]
we should probably include a styleguide as well at some point

https://github.com/atom/atom/blob/master/CONTRIBUTING.md

**Comment by chrstngyn** [comment]
we do have a git commit style guide from port of mars that we could add to our comses wiki https://github.com/virtualcommons/port-of-mars/wiki/Semantic-Commit-Messages

**Comment by alee** [comment]
> we do have a git commit style guide from port of mars that we could add to our comses wiki https://github.com/virtualcommons/port-of-mars/wiki/Semantic-Commit-Messages

Sounds good! I like the atom contributing guide as a baseline. I'm considering if we should strip out the editors@comses.net email and replace it with the comses.net contact form, thoughts on that? Trying to minimize our spam :sweat_smile:

**Comment by chrstngyn** [comment]
editing it here https://www.notion.so/gbci/CONTRIBUTING-md-9d9b709b7fa34883acc3576467451103 so I can easily export to markdown

**Review by alee — CHANGES_REQUESTED** [review]
Thanks Christine! However the text duplicated across both these files creates an update problem, changes have to be propagated from one to the other if we ever modify them... 

We could consolidate everything in CONTRIBUTING.md and have a link from the README to CONTRIBUTING.md or make CONTRIBUTING.md more technical mumbo jumbo on how to contribute via GitHub to this repo (e.g., semantic commit messages, things that should be an issue / PR, small self-contained commits, tests) in contrast to contributing to the comses.net community which would live in the README (like it is now).

I think I lean towards the latter, keeping CONTRIBUTING.md more technical and process oriented and the README how to contribute stuff as it is.. thoughts?

**Comment by chrstngyn** [comment]
That's a good point. We can link to CONTRIBUTING.md within README / Active Development to direct members to CONTRIBUTING.md for people who want to find more detailed technical/process oriented info. 

Incoming changes:

- Update README / Peer Review section
- Remove create pull request / submit issue Github documentation links from README / Active Development
- Continue to add technical / process-oriented info to CONTRIBUTING.md similar to atom's contribution guidelines
- anything else?

I've changed the settings on the notion page so anyone with the link can edit as well. After it is finalized, the page can be exported as a .md file.

**Pull request merged**
